version: 2

sources:
  - name: raw
    database: INSTACART_DB
    schema: RAW
    tables:
      - name: aisles
      - name: departments
      - name: orders
      - name: order_products_prior
      - name: order_products_train
      - name: products

models:
  - name: dim_products
    description: "Dimension table with enriched product info"
    columns:
      - name: product_id
      - name: product_name
      - name: aisle_id
      - name: aisle_name
      - name: department_id
      - name: department_name

  - name: instacart_orders
    description: "Raw order data with user and time info"
    columns:
      - name: order_id
        tests: [not_null, unique]

  - name: dim_orders
    description: "Cleaned and renamed version of the orders table."
    columns:
      - name: order_id
        description: "Unique identifier for each order"
      - name: user_id
        description: "Unique identifier for the user"
      - name: eval_set
        description: "Indicates whether the order is in the train, test, or prior set"
      - name: order_number
        description: "Sequence number of the order for the user"
      - name: order_day_of_week
        description: "Day of the week the order was placed"
      - name: order_hour_of_day
        description: "Hour of the day the order was placed"
      - name: days_since_prior_order
        description: "Number of days since the previous order"

  - name: fct_orders
    description: "Fact table of orders with aggregated product info"
    columns:
      - name: order_id
        description: "Unique ID for the order"
      - name: user_id
        description: "ID of the user who placed the order"
      - name: eval_set
        description: "Set this order belongs to (prior, train, test)"
      - name: order_number
        description: "The nth order placed by the user"
      - name: order_dow
        description: "Day of the week order was placed"
      - name: order_hour_of_day
        description: "Hour of the day order was placed"
      - name: days_since_prior_order
        description: "Days since the user’s previous order"
      - name: total_products
        description: "Total products in this order"
      - name: total_reordered
        description: "Number of products that were reordered"
