# models/schema.yml

description: |
  Description: Metadata and tests for Instacart data models
  → Defines raw sources and column-level metadata for curated models used in feature engineering and prediction.
  → Includes documentation for dimensional, fact, and ML-specific models.

version: 2

sources:
  - name: raw
    database: INSTACART_DB
    schema: RAW
    tables:
      - name: aisles
      - name: departments
      - name: orders
      - name: order_products_prior
      - name: order_products_train
      - name: products

models:
  - name: dim_products
    description: "Enriched product dimension with joins → Adds aisle and department names to the products table for better readability."
    columns:
      - name: product_id
      - name: product_name
      - name: aisle_id
      - name: aisle_name
      - name: department_id
      - name: department_name

  - name: instacart_orders
    description: "Raw order data with user and time info"
    columns:
      - name: order_id
        tests: [not_null, unique]

  - name: dim_orders
    description: | 
      Cleaned version of orders table 
      → Renames and standardizes columns from the raw orders table for clarity (e.g., order_dow → order_day_of_week).
    columns:
      - name: order_id
        description: "Unique identifier for each order"
      - name: user_id
        description: "Unique identifier for the user"
      - name: eval_set
        description: "Indicates whether the order is in the train, test, or prior set"
      - name: order_number
        description: "Sequence number of the order for the user"
      - name: order_day_of_week
        description: "Day of the week the order was placed"
      - name: order_hour_of_day
        description: "Hour of the day the order was placed"
      - name: days_since_prior_order
        description: "Number of days since the previous order"

  - name: fct_orders
    description: "Aggregates order facts → Adds product-level aggregates to each order: total items and how many were reordered."
    columns:
      - name: order_id
        description: "Unique ID for the order"
      - name: user_id
        description: "ID of the user who placed the order"
      - name: eval_set
        description: "Set this order belongs to (prior, train, test)"
      - name: order_number
        description: "The nth order placed by the user"
      - name: order_dow
        description: "Day of the week order was placed"
      - name: order_hour_of_day
        description: "Hour of the day order was placed"
      - name: days_since_prior_order
        description: "Days since the user’s previous order"
      - name: total_products
        description: "Total products in this order"
      - name: total_reordered
        description: "Number of products that were reordered"

  - name: fct_reorder_training_data
    description: |
      Creates ML training dataset
      → Labels each user-product pair with 1 or 0 depending on whether that product was reordered 
        in the user’s train order (most recent order among training users only) → used as ML training dataset.

      In the orders.csv file, each order is assigned an eval_set value.
        - prior → historical orders used for feature engineering.
        - train → the user’s most recent order, used for training your model.
        - test → the user’s most recent order, without labels, used for prediction.
    columns:
      - name: user_id
        description: "ID of the user"
      - name: product_id
        description: "ID of the product"
      - name: total_orders
        description: "How many times the user ordered this product"
      - name: total_reorders
        description: "How many times the product was reordered"
      - name: reorder_rate
        description: "Average reorder rate"
      - name: max_order_number
        description: "User’s latest order number for this product"
      - name: days_since_last_order
        description: "Recency of user’s last order of this product"
      - name: reordered_label
        description: "Binary label: 1 if reordered in current train order, else 0"

  - name: instacart_training_input
    description: |
      Filtered dataset passed into trained model
      → Filters fct_user_product_features to include only user-product pairs with at least 2 prior orders. 
        Pairs are then passed into the trained model to generate reorder predictions.
    columns:
      - name: user_id
      - name: product_id
      - name: total_orders
      - name: total_reorders
      - name: reorder_rate
      - name: max_order_number
      - name: days_since_last_order
      - name: reordered_label

  - name: instacart_predictions_output
    description: |
      Srores predicted reorder probabilities
      → Stores predicted reorder probabilities for each user-product pair from the inference set (test users as labeled in orders.csv).
        (Currently empty — to be populated by the Snowpark ML model.)

    columns:
      - name: user_id
      - name: product_id
      - name: reorder_probability
        description: "Model-predicted probability of reorder"
      - name: scored_at
        description: "Timestamp when prediction was generated"
